import type {
  AdminMetric,
  Branch,
  BranchStock,
  CatalogItem,
  CostTrackingData,
  DashboardData,
  BillPaymentBatch,
  DirectDebitMandate,
  DirectDebitRun,
  DigitalReceiptShare,
  FinancialCalendarDay,
  InventoryCategory,
  InventoryItem,
  Invoice,
  CustomerInvoice,
  PayableBill,
  MenuItem,
  Notification,
  Organization,
  PurchaseOrder,
  Recipe,
  RestaurantTable,
  SalesShift,
  SocialAccount,
  SocialPost,
  SocialTemplate,
  SmartSavingsFeature,
  StockMovement,
  Supplier,
  Transfer,
  WasteLog,
} from "@/types/domain";

export const demoOrganization: Organization = {
  id: "00000000-0000-4000-8000-000000000001",
  name: "مطعم إيوان",
  slug: "iwan-demo",
  plan: "Growth",
  status: "trial",
};

export const demoBranches: Branch[] = [
  {
    id: "00000000-0000-4000-8000-000000000101",
    organizationId: demoOrganization.id,
    name: "فرع شارع عبد القادر الحسيني",
    city: "غزة",
    address: "شارع عبد القادر الحسيني",
    manager: "سارة النجار",
    status: "active",
  },
  {
    id: "00000000-0000-4000-8000-000000000102",
    organizationId: demoOrganization.id,
    name: "فرع الرمال",
    city: "غزة",
    address: "الرمال، شارع عمر المختار",
    manager: "محمود عوض",
    status: "active",
  },
];

export const demoSuppliers: Supplier[] = [
  {
    id: "00000000-0000-4000-8000-000000000201",
    organizationId: demoOrganization.id,
    name: "مورد الدجاج",
    phone: "+970 599 111 222",
    email: "chicken@example.com",
    address: "سوق الجملة",
    notes: "توريد يومي صباحًا",
    status: "active",
    priceRisk: 18,
  },
  {
    id: "00000000-0000-4000-8000-000000000202",
    organizationId: demoOrganization.id,
    name: "مورد الخضار",
    phone: "+970 599 333 444",
    email: "veg@example.com",
    address: "سوق فراس",
    status: "active",
    priceRisk: 7,
  },
  {
    id: "00000000-0000-4000-8000-000000000203",
    organizationId: demoOrganization.id,
    name: "مورد التغليف",
    phone: "+970 599 555 666",
    email: "pack@example.com",
    address: "المنطقة الصناعية",
    status: "active",
    priceRisk: 4,
  },
  {
    id: "00000000-0000-4000-8000-000000000204",
    organizationId: demoOrganization.id,
    name: "مورد اللحوم والأسماك",
    phone: "+970 599 222 777",
    email: "meat@example.com",
    address: "سوق الزاوية",
    notes: "لحوم طازجة ومجمدات بحرية",
    status: "active",
    priceRisk: 14,
  },
  {
    id: "00000000-0000-4000-8000-000000000205",
    organizationId: demoOrganization.id,
    name: "مورد الألبان والمخبوزات",
    phone: "+970 599 444 777",
    email: "dairy@example.com",
    address: "النصر",
    notes: "توريد صباحي للخبز والألبان",
    status: "active",
    priceRisk: 6,
  },
  {
    id: "00000000-0000-4000-8000-000000000206",
    organizationId: demoOrganization.id,
    name: "مورد البهارات والصوصات",
    phone: "+970 599 666 777",
    email: "spices@example.com",
    address: "سوق فراس",
    status: "active",
    priceRisk: 9,
  },
  {
    id: "00000000-0000-4000-8000-000000000207",
    organizationId: demoOrganization.id,
    name: "مورد المشروبات والقهوة",
    phone: "+970 599 777 888",
    email: "drinks@example.com",
    address: "تل الهوا",
    status: "active",
    priceRisk: 5,
  },
  {
    id: "00000000-0000-4000-8000-000000000208",
    organizationId: demoOrganization.id,
    name: "مورد النظافة والتشغيل",
    phone: "+970 599 888 999",
    email: "clean@example.com",
    address: "المنطقة الصناعية",
    status: "active",
    priceRisk: 3,
  },
];

export const demoCategories: InventoryCategory[] = [
  { id: "cat-protein", organizationId: demoOrganization.id, name: "بروتين" },
  { id: "cat-meat", organizationId: demoOrganization.id, name: "لحوم وأسماك" },
  { id: "cat-vegetables", organizationId: demoOrganization.id, name: "خضار طازجة" },
  { id: "cat-fruits", organizationId: demoOrganization.id, name: "فواكه وحمضيات" },
  { id: "cat-herbs", organizationId: demoOrganization.id, name: "أعشاب طازجة" },
  { id: "cat-spices", organizationId: demoOrganization.id, name: "بهارات وتوابل" },
  { id: "cat-grains", organizationId: demoOrganization.id, name: "حبوب ونشويات" },
  { id: "cat-bakery", organizationId: demoOrganization.id, name: "مخبوزات" },
  { id: "cat-oils", organizationId: demoOrganization.id, name: "زيوت" },
  { id: "cat-frozen", organizationId: demoOrganization.id, name: "مجمدات" },
  { id: "cat-dairy", organizationId: demoOrganization.id, name: "أجبان" },
  { id: "cat-sauce", organizationId: demoOrganization.id, name: "صوصات" },
  { id: "cat-beverages", organizationId: demoOrganization.id, name: "مشروبات وقهوة" },
  { id: "cat-packaging", organizationId: demoOrganization.id, name: "تغليف" },
  { id: "cat-disposables", organizationId: demoOrganization.id, name: "مستهلكات تقديم" },
  { id: "cat-cleaning", organizationId: demoOrganization.id, name: "نظافة وتعقيم" },
  { id: "cat-operations", organizationId: demoOrganization.id, name: "تشغيل وصيانة" },
];

export const demoInventoryItems: InventoryItem[] = [
  {
    id: "item-chicken",
    organizationId: demoOrganization.id,
    name: "دجاج",
    categoryId: "cat-protein",
    categoryName: "بروتين",
    purchaseUnit: "كرتونة",
    usageUnit: "كغم",
    lastPurchasePrice: 18,
    averageCost: 17.2,
    minimumQuantity: 40,
    primarySupplierId: demoSuppliers[0].id,
    primarySupplierName: demoSuppliers[0].name,
    sku: "CHK-001",
    notes: "صدور دجاج مجمدة",
    isActive: true,
  },
  {
    id: "item-rice",
    organizationId: demoOrganization.id,
    name: "أرز",
    categoryId: "cat-grains",
    categoryName: "حبوب ونشويات",
    purchaseUnit: "كيس",
    usageUnit: "كغم",
    lastPurchasePrice: 6,
    averageCost: 5.7,
    minimumQuantity: 60,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    isActive: true,
  },
  {
    id: "item-oil",
    organizationId: demoOrganization.id,
    name: "زيت",
    categoryId: "cat-oils",
    categoryName: "زيوت",
    purchaseUnit: "تنكة",
    usageUnit: "لتر",
    lastPurchasePrice: 9,
    averageCost: 8.6,
    minimumQuantity: 30,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    isActive: true,
  },
  {
    id: "item-potato",
    organizationId: demoOrganization.id,
    name: "بطاطا",
    categoryId: "cat-grains",
    categoryName: "حبوب ونشويات",
    purchaseUnit: "كيس",
    usageUnit: "كغم",
    lastPurchasePrice: 3.5,
    averageCost: 3.2,
    minimumQuantity: 35,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    isActive: true,
  },
  {
    id: "item-bun",
    organizationId: demoOrganization.id,
    name: "خبز برجر",
    categoryId: "cat-grains",
    categoryName: "حبوب ونشويات",
    purchaseUnit: "كيس",
    usageUnit: "قطعة",
    lastPurchasePrice: 0.75,
    averageCost: 0.72,
    minimumQuantity: 120,
    primarySupplierId: demoSuppliers[2].id,
    primarySupplierName: demoSuppliers[2].name,
    isActive: true,
  },
  {
    id: "item-hot-sauce",
    organizationId: demoOrganization.id,
    name: "صوص حار",
    categoryId: "cat-sauce",
    categoryName: "صوصات",
    purchaseUnit: "غالون",
    usageUnit: "مل",
    lastPurchasePrice: 0.04,
    averageCost: 0.038,
    minimumQuantity: 5000,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    isActive: true,
  },
  {
    id: "item-cheese",
    organizationId: demoOrganization.id,
    name: "جبنة",
    categoryId: "cat-dairy",
    categoryName: "أجبان",
    purchaseUnit: "كرتونة",
    usageUnit: "شريحة",
    lastPurchasePrice: 0.9,
    averageCost: 0.84,
    minimumQuantity: 100,
    primarySupplierId: demoSuppliers[0].id,
    primarySupplierName: demoSuppliers[0].name,
    isActive: true,
  },
  {
    id: "item-packaging",
    organizationId: demoOrganization.id,
    name: "علب تغليف",
    categoryId: "cat-packaging",
    categoryName: "تغليف",
    purchaseUnit: "كرتونة",
    usageUnit: "قطعة",
    lastPurchasePrice: 0.35,
    averageCost: 0.33,
    minimumQuantity: 300,
    primarySupplierId: demoSuppliers[2].id,
    primarySupplierName: demoSuppliers[2].name,
    isActive: true,
  },
  {
    id: "item-beef",
    organizationId: demoOrganization.id,
    name: "لحم عجل",
    categoryId: "cat-meat",
    categoryName: "لحوم وأسماك",
    purchaseUnit: "كرتونة",
    usageUnit: "كغم",
    lastPurchasePrice: 46,
    averageCost: 44.5,
    minimumQuantity: 20,
    primarySupplierId: demoSuppliers[3].id,
    primarySupplierName: demoSuppliers[3].name,
    sku: "MET-001",
    notes: "مناسب للبرجر والستيك",
    isActive: true,
  },
  {
    id: "item-fish-fillet",
    organizationId: demoOrganization.id,
    name: "فيليه سمك",
    categoryId: "cat-meat",
    categoryName: "لحوم وأسماك",
    purchaseUnit: "كرتونة",
    usageUnit: "كغم",
    lastPurchasePrice: 31,
    averageCost: 29.8,
    minimumQuantity: 12,
    primarySupplierId: demoSuppliers[3].id,
    primarySupplierName: demoSuppliers[3].name,
    sku: "SEA-010",
    isActive: true,
  },
  {
    id: "item-eggs",
    organizationId: demoOrganization.id,
    name: "بيض",
    categoryId: "cat-protein",
    categoryName: "بروتين",
    purchaseUnit: "طبق",
    usageUnit: "حبة",
    lastPurchasePrice: 0.55,
    averageCost: 0.52,
    minimumQuantity: 180,
    primarySupplierId: demoSuppliers[4].id,
    primarySupplierName: demoSuppliers[4].name,
    sku: "EGG-030",
    isActive: true,
  },
  {
    id: "item-lettuce",
    organizationId: demoOrganization.id,
    name: "خس",
    categoryId: "cat-vegetables",
    categoryName: "خضار طازجة",
    purchaseUnit: "صندوق",
    usageUnit: "كغم",
    lastPurchasePrice: 4.2,
    averageCost: 4,
    minimumQuantity: 12,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    sku: "VEG-011",
    isActive: true,
  },
  {
    id: "item-tomato",
    organizationId: demoOrganization.id,
    name: "بندورة",
    categoryId: "cat-vegetables",
    categoryName: "خضار طازجة",
    purchaseUnit: "صندوق",
    usageUnit: "كغم",
    lastPurchasePrice: 3.8,
    averageCost: 3.4,
    minimumQuantity: 25,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    sku: "VEG-012",
    isActive: true,
  },
  {
    id: "item-cucumber",
    organizationId: demoOrganization.id,
    name: "خيار",
    categoryId: "cat-vegetables",
    categoryName: "خضار طازجة",
    purchaseUnit: "صندوق",
    usageUnit: "كغم",
    lastPurchasePrice: 3.2,
    averageCost: 3.1,
    minimumQuantity: 18,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    sku: "VEG-013",
    isActive: true,
  },
  {
    id: "item-onion",
    organizationId: demoOrganization.id,
    name: "بصل",
    categoryId: "cat-vegetables",
    categoryName: "خضار طازجة",
    purchaseUnit: "كيس",
    usageUnit: "كغم",
    lastPurchasePrice: 2.4,
    averageCost: 2.2,
    minimumQuantity: 30,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    sku: "VEG-014",
    isActive: true,
  },
  {
    id: "item-garlic",
    organizationId: demoOrganization.id,
    name: "ثوم",
    categoryId: "cat-vegetables",
    categoryName: "خضار طازجة",
    purchaseUnit: "كيس",
    usageUnit: "كغم",
    lastPurchasePrice: 12,
    averageCost: 11.4,
    minimumQuantity: 5,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    sku: "VEG-015",
    isActive: true,
  },
  {
    id: "item-lemon",
    organizationId: demoOrganization.id,
    name: "ليمون",
    categoryId: "cat-fruits",
    categoryName: "فواكه وحمضيات",
    purchaseUnit: "صندوق",
    usageUnit: "كغم",
    lastPurchasePrice: 5.5,
    averageCost: 5,
    minimumQuantity: 10,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    sku: "FRT-021",
    isActive: true,
  },
  {
    id: "item-parsley",
    organizationId: demoOrganization.id,
    name: "بقدونس",
    categoryId: "cat-herbs",
    categoryName: "أعشاب طازجة",
    purchaseUnit: "ربطة",
    usageUnit: "ربطة",
    lastPurchasePrice: 1.2,
    averageCost: 1.1,
    minimumQuantity: 25,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    sku: "HRB-001",
    isActive: true,
  },
  {
    id: "item-coriander",
    organizationId: demoOrganization.id,
    name: "كزبرة",
    categoryId: "cat-herbs",
    categoryName: "أعشاب طازجة",
    purchaseUnit: "ربطة",
    usageUnit: "ربطة",
    lastPurchasePrice: 1.1,
    averageCost: 1,
    minimumQuantity: 20,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    sku: "HRB-002",
    isActive: true,
  },
  {
    id: "item-frozen-fries",
    organizationId: demoOrganization.id,
    name: "بطاطا مجمدة",
    categoryId: "cat-frozen",
    categoryName: "مجمدات",
    purchaseUnit: "كرتونة",
    usageUnit: "كغم",
    lastPurchasePrice: 7.5,
    averageCost: 7.2,
    minimumQuantity: 45,
    primarySupplierId: demoSuppliers[3].id,
    primarySupplierName: demoSuppliers[3].name,
    sku: "FRZ-001",
    isActive: true,
  },
  {
    id: "item-flour",
    organizationId: demoOrganization.id,
    name: "طحين",
    categoryId: "cat-grains",
    categoryName: "حبوب ونشويات",
    purchaseUnit: "كيس",
    usageUnit: "كغم",
    lastPurchasePrice: 3.1,
    averageCost: 3,
    minimumQuantity: 50,
    primarySupplierId: demoSuppliers[4].id,
    primarySupplierName: demoSuppliers[4].name,
    sku: "GRN-010",
    isActive: true,
  },
  {
    id: "item-sugar",
    organizationId: demoOrganization.id,
    name: "سكر",
    categoryId: "cat-grains",
    categoryName: "حبوب ونشويات",
    purchaseUnit: "كيس",
    usageUnit: "كغم",
    lastPurchasePrice: 4.4,
    averageCost: 4.2,
    minimumQuantity: 35,
    primarySupplierId: demoSuppliers[6].id,
    primarySupplierName: demoSuppliers[6].name,
    sku: "GRN-011",
    isActive: true,
  },
  {
    id: "item-pasta",
    organizationId: demoOrganization.id,
    name: "معكرونة",
    categoryId: "cat-grains",
    categoryName: "حبوب ونشويات",
    purchaseUnit: "كرتونة",
    usageUnit: "كغم",
    lastPurchasePrice: 5.8,
    averageCost: 5.4,
    minimumQuantity: 25,
    primarySupplierId: demoSuppliers[1].id,
    primarySupplierName: demoSuppliers[1].name,
    sku: "GRN-012",
    isActive: true,
  },
  {
    id: "item-tortilla",
    organizationId: demoOrganization.id,
    name: "خبز تورتيلا",
    categoryId: "cat-bakery",
    categoryName: "مخبوزات",
    purchaseUnit: "كيس",
    usageUnit: "قطعة",
    lastPurchasePrice: 0.65,
    averageCost: 0.6,
    minimumQuantity: 160,
    primarySupplierId: demoSuppliers[4].id,
    primarySupplierName: demoSuppliers[4].name,
    sku: "BAK-001",
    isActive: true,
  },
  {
    id: "item-pita",
    organizationId: demoOrganization.id,
    name: "خبز عربي",
    categoryId: "cat-bakery",
    categoryName: "مخبوزات",
    purchaseUnit: "كيس",
    usageUnit: "قطعة",
    lastPurchasePrice: 0.35,
    averageCost: 0.32,
    minimumQuantity: 220,
    primarySupplierId: demoSuppliers[4].id,
    primarySupplierName: demoSuppliers[4].name,
    sku: "BAK-002",
    isActive: true,
  },
  {
    id: "item-milk",
    organizationId: demoOrganization.id,
    name: "حليب",
    categoryId: "cat-dairy",
    categoryName: "أجبان",
    purchaseUnit: "كرتونة",
    usageUnit: "لتر",
    lastPurchasePrice: 5.2,
    averageCost: 5,
    minimumQuantity: 30,
    primarySupplierId: demoSuppliers[4].id,
    primarySupplierName: demoSuppliers[4].name,
    sku: "DRY-001",
    isActive: true,
  },
  {
    id: "item-yogurt",
    organizationId: demoOrganization.id,
    name: "لبن",
    categoryId: "cat-dairy",
    categoryName: "أجبان",
    purchaseUnit: "سطل",
    usageUnit: "كغم",
    lastPurchasePrice: 7,
    averageCost: 6.7,
    minimumQuantity: 18,
    primarySupplierId: demoSuppliers[4].id,
    primarySupplierName: demoSuppliers[4].name,
    sku: "DRY-002",
    isActive: true,
  },
  {
    id: "item-butter",
    organizationId: demoOrganization.id,
    name: "زبدة",
    categoryId: "cat-dairy",
    categoryName: "أجبان",
    purchaseUnit: "كرتونة",
    usageUnit: "كغم",
    lastPurchasePrice: 24,
    averageCost: 23.5,
    minimumQuantity: 8,
    primarySupplierId: demoSuppliers[4].id,
    primarySupplierName: demoSuppliers[4].name,
    sku: "DRY-003",
    isActive: true,
  },
  {
    id: "item-mozzarella",
    organizationId: demoOrganization.id,
    name: "جبنة موزاريلا",
    categoryId: "cat-dairy",
    categoryName: "أجبان",
    purchaseUnit: "كرتونة",
    usageUnit: "كغم",
    lastPurchasePrice: 28,
    averageCost: 27,
    minimumQuantity: 16,
    primarySupplierId: demoSuppliers[4].id,
    primarySupplierName: demoSuppliers[4].name,
    sku: "DRY-004",
    isActive: true,
  },
  {
    id: "item-salt",
    organizationId: demoOrganization.id,
    name: "ملح",
    categoryId: "cat-spices",
    categoryName: "بهارات وتوابل",
    purchaseUnit: "كيس",
    usageUnit: "كغم",
    lastPurchasePrice: 1.4,
    averageCost: 1.3,
    minimumQuantity: 18,
    primarySupplierId: demoSuppliers[5].id,
    primarySupplierName: demoSuppliers[5].name,
    sku: "SPC-001",
    isActive: true,
  },
  {
    id: "item-black-pepper",
    organizationId: demoOrganization.id,
    name: "فلفل أسود",
    categoryId: "cat-spices",
    categoryName: "بهارات وتوابل",
    purchaseUnit: "كغم",
    usageUnit: "غرام",
    lastPurchasePrice: 0.045,
    averageCost: 0.043,
    minimumQuantity: 2500,
    primarySupplierId: demoSuppliers[5].id,
    primarySupplierName: demoSuppliers[5].name,
    sku: "SPC-002",
    isActive: true,
  },
  {
    id: "item-paprika",
    organizationId: demoOrganization.id,
    name: "بابريكا",
    categoryId: "cat-spices",
    categoryName: "بهارات وتوابل",
    purchaseUnit: "كغم",
    usageUnit: "غرام",
    lastPurchasePrice: 0.038,
    averageCost: 0.036,
    minimumQuantity: 3000,
    primarySupplierId: demoSuppliers[5].id,
    primarySupplierName: demoSuppliers[5].name,
    sku: "SPC-003",
    isActive: true,
  },
  {
    id: "item-curry",
    organizationId: demoOrganization.id,
    name: "كاري",
    categoryId: "cat-spices",
    categoryName: "بهارات وتوابل",
    purchaseUnit: "كغم",
    usageUnit: "غرام",
    lastPurchasePrice: 0.05,
    averageCost: 0.048,
    minimumQuantity: 1800,
    primarySupplierId: demoSuppliers[5].id,
    primarySupplierName: demoSuppliers[5].name,
    sku: "SPC-004",
    isActive: true,
  },
  {
    id: "item-soy-sauce",
    organizationId: demoOrganization.id,
    name: "صويا صوص",
    categoryId: "cat-sauce",
    categoryName: "صوصات",
    purchaseUnit: "غالون",
    usageUnit: "مل",
    lastPurchasePrice: 0.035,
    averageCost: 0.033,
    minimumQuantity: 4000,
    primarySupplierId: demoSuppliers[5].id,
    primarySupplierName: demoSuppliers[5].name,
    sku: "SAU-010",
    isActive: true,
  },
  {
    id: "item-mayo",
    organizationId: demoOrganization.id,
    name: "مايونيز",
    categoryId: "cat-sauce",
    categoryName: "صوصات",
    purchaseUnit: "غالون",
    usageUnit: "مل",
    lastPurchasePrice: 0.03,
    averageCost: 0.028,
    minimumQuantity: 6000,
    primarySupplierId: demoSuppliers[5].id,
    primarySupplierName: demoSuppliers[5].name,
    sku: "SAU-011",
    isActive: true,
  },
  {
    id: "item-ketchup",
    organizationId: demoOrganization.id,
    name: "كاتشب",
    categoryId: "cat-sauce",
    categoryName: "صوصات",
    purchaseUnit: "غالون",
    usageUnit: "مل",
    lastPurchasePrice: 0.026,
    averageCost: 0.025,
    minimumQuantity: 7000,
    primarySupplierId: demoSuppliers[5].id,
    primarySupplierName: demoSuppliers[5].name,
    sku: "SAU-012",
    isActive: true,
  },
  {
    id: "item-tahini",
    organizationId: demoOrganization.id,
    name: "طحينة",
    categoryId: "cat-sauce",
    categoryName: "صوصات",
    purchaseUnit: "سطل",
    usageUnit: "كغم",
    lastPurchasePrice: 18,
    averageCost: 17.5,
    minimumQuantity: 12,
    primarySupplierId: demoSuppliers[5].id,
    primarySupplierName: demoSuppliers[5].name,
    sku: "SAU-013",
    isActive: true,
  },
  {
    id: "item-water",
    organizationId: demoOrganization.id,
    name: "مياه معدنية",
    categoryId: "cat-beverages",
    categoryName: "مشروبات وقهوة",
    purchaseUnit: "كرتونة",
    usageUnit: "عبوة",
    lastPurchasePrice: 1.1,
    averageCost: 1,
    minimumQuantity: 240,
    primarySupplierId: demoSuppliers[6].id,
    primarySupplierName: demoSuppliers[6].name,
    sku: "BEV-001",
    isActive: true,
  },
  {
    id: "item-cola",
    organizationId: demoOrganization.id,
    name: "مشروبات غازية",
    categoryId: "cat-beverages",
    categoryName: "مشروبات وقهوة",
    purchaseUnit: "كرتونة",
    usageUnit: "علبة",
    lastPurchasePrice: 2.2,
    averageCost: 2.1,
    minimumQuantity: 180,
    primarySupplierId: demoSuppliers[6].id,
    primarySupplierName: demoSuppliers[6].name,
    sku: "BEV-002",
    isActive: true,
  },
  {
    id: "item-coffee-beans",
    organizationId: demoOrganization.id,
    name: "حبوب قهوة",
    categoryId: "cat-beverages",
    categoryName: "مشروبات وقهوة",
    purchaseUnit: "كيس",
    usageUnit: "كغم",
    lastPurchasePrice: 58,
    averageCost: 56,
    minimumQuantity: 10,
    primarySupplierId: demoSuppliers[6].id,
    primarySupplierName: demoSuppliers[6].name,
    sku: "BEV-003",
    isActive: true,
  },
  {
    id: "item-tea",
    organizationId: demoOrganization.id,
    name: "شاي",
    categoryId: "cat-beverages",
    categoryName: "مشروبات وقهوة",
    purchaseUnit: "كرتونة",
    usageUnit: "كيس",
    lastPurchasePrice: 0.18,
    averageCost: 0.16,
    minimumQuantity: 500,
    primarySupplierId: demoSuppliers[6].id,
    primarySupplierName: demoSuppliers[6].name,
    sku: "BEV-004",
    isActive: true,
  },
  {
    id: "item-paper-cups",
    organizationId: demoOrganization.id,
    name: "أكواب ورقية",
    categoryId: "cat-disposables",
    categoryName: "مستهلكات تقديم",
    purchaseUnit: "كرتونة",
    usageUnit: "قطعة",
    lastPurchasePrice: 0.22,
    averageCost: 0.2,
    minimumQuantity: 600,
    primarySupplierId: demoSuppliers[2].id,
    primarySupplierName: demoSuppliers[2].name,
    sku: "DSP-001",
    isActive: true,
  },
  {
    id: "item-lids",
    organizationId: demoOrganization.id,
    name: "أغطية أكواب",
    categoryId: "cat-disposables",
    categoryName: "مستهلكات تقديم",
    purchaseUnit: "كرتونة",
    usageUnit: "قطعة",
    lastPurchasePrice: 0.08,
    averageCost: 0.075,
    minimumQuantity: 600,
    primarySupplierId: demoSuppliers[2].id,
    primarySupplierName: demoSuppliers[2].name,
    sku: "DSP-002",
    isActive: true,
  },
  {
    id: "item-napkins",
    organizationId: demoOrganization.id,
    name: "مناديل",
    categoryId: "cat-disposables",
    categoryName: "مستهلكات تقديم",
    purchaseUnit: "كرتونة",
    usageUnit: "رزمة",
    lastPurchasePrice: 3.5,
    averageCost: 3.3,
    minimumQuantity: 80,
    primarySupplierId: demoSuppliers[2].id,
    primarySupplierName: demoSuppliers[2].name,
    sku: "DSP-003",
    isActive: true,
  },
  {
    id: "item-gloves",
    organizationId: demoOrganization.id,
    name: "قفازات",
    categoryId: "cat-disposables",
    categoryName: "مستهلكات تقديم",
    purchaseUnit: "كرتونة",
    usageUnit: "علبة",
    lastPurchasePrice: 12,
    averageCost: 11.5,
    minimumQuantity: 18,
    primarySupplierId: demoSuppliers[7].id,
    primarySupplierName: demoSuppliers[7].name,
    sku: "DSP-004",
    isActive: true,
  },
  {
    id: "item-foil",
    organizationId: demoOrganization.id,
    name: "ورق ألمنيوم",
    categoryId: "cat-packaging",
    categoryName: "تغليف",
    purchaseUnit: "كرتونة",
    usageUnit: "رول",
    lastPurchasePrice: 18,
    averageCost: 17,
    minimumQuantity: 10,
    primarySupplierId: demoSuppliers[2].id,
    primarySupplierName: demoSuppliers[2].name,
    sku: "PKG-010",
    isActive: true,
  },
  {
    id: "item-paper-bags",
    organizationId: demoOrganization.id,
    name: "أكياس ورقية",
    categoryId: "cat-packaging",
    categoryName: "تغليف",
    purchaseUnit: "كرتونة",
    usageUnit: "قطعة",
    lastPurchasePrice: 0.28,
    averageCost: 0.26,
    minimumQuantity: 400,
    primarySupplierId: demoSuppliers[2].id,
    primarySupplierName: demoSuppliers[2].name,
    sku: "PKG-011",
    isActive: true,
  },
  {
    id: "item-receipt-paper",
    organizationId: demoOrganization.id,
    name: "رولات فواتير",
    categoryId: "cat-operations",
    categoryName: "تشغيل وصيانة",
    purchaseUnit: "كرتونة",
    usageUnit: "رول",
    lastPurchasePrice: 4,
    averageCost: 3.8,
    minimumQuantity: 20,
    primarySupplierId: demoSuppliers[7].id,
    primarySupplierName: demoSuppliers[7].name,
    sku: "OPS-001",
    notes: "للطابعات الحرارية عند الحاجة",
    isActive: true,
  },
  {
    id: "item-gas-cylinder",
    organizationId: demoOrganization.id,
    name: "أسطوانة غاز",
    categoryId: "cat-operations",
    categoryName: "تشغيل وصيانة",
    purchaseUnit: "أسطوانة",
    usageUnit: "أسطوانة",
    lastPurchasePrice: 72,
    averageCost: 70,
    minimumQuantity: 3,
    primarySupplierId: demoSuppliers[7].id,
    primarySupplierName: demoSuppliers[7].name,
    sku: "OPS-002",
    isActive: true,
  },
  {
    id: "item-sanitizer",
    organizationId: demoOrganization.id,
    name: "معقم أسطح",
    categoryId: "cat-cleaning",
    categoryName: "نظافة وتعقيم",
    purchaseUnit: "غالون",
    usageUnit: "لتر",
    lastPurchasePrice: 9,
    averageCost: 8.5,
    minimumQuantity: 12,
    primarySupplierId: demoSuppliers[7].id,
    primarySupplierName: demoSuppliers[7].name,
    sku: "CLN-001",
    isActive: true,
  },
  {
    id: "item-dish-soap",
    organizationId: demoOrganization.id,
    name: "سائل جلي",
    categoryId: "cat-cleaning",
    categoryName: "نظافة وتعقيم",
    purchaseUnit: "غالون",
    usageUnit: "لتر",
    lastPurchasePrice: 7,
    averageCost: 6.8,
    minimumQuantity: 15,
    primarySupplierId: demoSuppliers[7].id,
    primarySupplierName: demoSuppliers[7].name,
    sku: "CLN-002",
    isActive: true,
  },
  {
    id: "item-trash-bags",
    organizationId: demoOrganization.id,
    name: "أكياس نفايات",
    categoryId: "cat-cleaning",
    categoryName: "نظافة وتعقيم",
    purchaseUnit: "كرتونة",
    usageUnit: "رول",
    lastPurchasePrice: 8,
    averageCost: 7.5,
    minimumQuantity: 25,
    primarySupplierId: demoSuppliers[7].id,
    primarySupplierName: demoSuppliers[7].name,
    sku: "CLN-003",
    isActive: true,
  },
];

const branchStockOverrides: Record<string, [number, number, number, number]> = {
  "item-chicken": [32, 6, 54, 8],
  "item-rice": [87, 12, 64, 9],
  "item-oil": [19, 2, 42, 5],
  "item-bun": [210, 22, 185, 18],
  "item-packaging": [340, 42, 260, 30],
  "item-gas-cylinder": [2, 0, 4, 0],
  "item-coffee-beans": [7, 1, 16, 2],
  "item-gloves": [12, 2, 21, 3],
};

export const demoBranchStock: BranchStock[] = demoInventoryItems.flatMap((item, index) => {
  const fallbackA = Math.max(Math.round(item.minimumQuantity * (1.35 + (index % 5) * 0.22)), 1);
  const fallbackB = Math.max(Math.round(item.minimumQuantity * (1.15 + (index % 4) * 0.18)), 1);
  const [quantityA, reservedA, quantityB, reservedB] = branchStockOverrides[item.id] ?? [
    fallbackA,
    Math.round(fallbackA * 0.08),
    fallbackB,
    Math.round(fallbackB * 0.07),
  ];

  return [
    {
      branchId: demoBranches[0].id,
      branchName: demoBranches[0].name,
      itemId: item.id,
      quantity: quantityA,
      reservedQuantity: reservedA,
    },
    {
      branchId: demoBranches[1].id,
      branchName: demoBranches[1].name,
      itemId: item.id,
      quantity: quantityB,
      reservedQuantity: reservedB,
    },
  ];
});

export const demoStockMovements: StockMovement[] = [
  {
    id: "mov-001",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    itemId: "item-chicken",
    itemName: "دجاج",
    movementType: "purchase",
    quantity: 80,
    unitCost: 18,
    totalCost: 1440,
    reference: "PO-1008",
    notes: "استلام من مورد الدجاج",
    createdAt: "2026-05-15T09:20:00Z",
  },
  {
    id: "mov-002",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    itemId: "item-oil",
    itemName: "زيت",
    movementType: "waste",
    quantity: -4,
    unitCost: 8.6,
    totalCost: -34.4,
    reference: "WST-204",
    notes: "انسكاب أثناء التحضير",
    createdAt: "2026-05-15T13:05:00Z",
  },
  {
    id: "mov-003",
    organizationId: demoOrganization.id,
    branchId: demoBranches[1].id,
    branchName: demoBranches[1].name,
    itemId: "item-packaging",
    itemName: "علب تغليف",
    movementType: "transfer_in",
    quantity: 120,
    unitCost: 0.33,
    totalCost: 39.6,
    reference: "TR-044",
    createdAt: "2026-05-14T16:40:00Z",
  },
  {
    id: "mov-004",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    itemId: "item-frozen-fries",
    itemName: "بطاطا مجمدة",
    movementType: "purchase",
    quantity: 90,
    unitCost: 7.5,
    totalCost: 675,
    reference: "PO-1010",
    notes: "تعزيز مخزون المجمدات لنهاية الأسبوع",
    createdAt: "2026-05-16T08:10:00Z",
  },
  {
    id: "mov-005",
    organizationId: demoOrganization.id,
    branchId: demoBranches[1].id,
    branchName: demoBranches[1].name,
    itemId: "item-coffee-beans",
    itemName: "حبوب قهوة",
    movementType: "purchase",
    quantity: 18,
    unitCost: 58,
    totalCost: 1044,
    reference: "PO-1011",
    notes: "توريد قهوة أسبوعي",
    createdAt: "2026-05-16T10:35:00Z",
  },
  {
    id: "mov-006",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    itemId: "item-lettuce",
    itemName: "خس",
    movementType: "waste",
    quantity: -3,
    unitCost: 4,
    totalCost: -12,
    reference: "WST-205",
    notes: "تلف أوراق بسبب التخزين",
    createdAt: "2026-05-16T12:05:00Z",
  },
  {
    id: "mov-007",
    organizationId: demoOrganization.id,
    branchId: demoBranches[1].id,
    branchName: demoBranches[1].name,
    itemId: "item-paper-cups",
    itemName: "أكواب ورقية",
    movementType: "adjustment",
    quantity: 120,
    unitCost: 0.2,
    totalCost: 24,
    reference: "ADJ-078",
    notes: "تسوية بعد جرد المستهلكات",
    createdAt: "2026-05-15T18:15:00Z",
  },
  {
    id: "mov-008",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    itemId: "item-gas-cylinder",
    itemName: "أسطوانة غاز",
    movementType: "purchase",
    quantity: 4,
    unitCost: 72,
    totalCost: 288,
    reference: "OPS-332",
    notes: "توريد غاز للتشغيل",
    createdAt: "2026-05-14T11:30:00Z",
  },
  {
    id: "mov-009",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    itemId: "item-chicken",
    itemName: "دجاج",
    movementType: "sale_usage",
    quantity: -2.12,
    unitCost: 17.2,
    totalCost: -36.46,
    reference: "C-2026-1001",
    notes: "خصم تلقائي من بيع وجبات دجاج وزِنجر",
    createdAt: "2026-05-16T13:20:00Z",
  },
  {
    id: "mov-010",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    itemId: "item-rice",
    itemName: "أرز",
    movementType: "sale_usage",
    quantity: -0.18,
    unitCost: 5.7,
    totalCost: -1.03,
    reference: "C-2026-1001",
    notes: "خصم تلقائي من وصفة وجبة دجاج تايلندي",
    createdAt: "2026-05-16T13:20:00Z",
  },
  {
    id: "mov-011",
    organizationId: demoOrganization.id,
    branchId: demoBranches[1].id,
    branchName: demoBranches[1].name,
    itemId: "item-packaging",
    itemName: "علب تغليف",
    movementType: "sale_usage",
    quantity: -5,
    unitCost: 0.33,
    totalCost: -1.65,
    reference: "C-2026-1002",
    notes: "خصم تغليف تلقائي مع فواتير البيع",
    createdAt: "2026-05-16T15:45:00Z",
  },
];

export const demoPurchaseOrders: PurchaseOrder[] = [
  {
    id: "PO-1009",
    organizationId: demoOrganization.id,
    supplierId: demoSuppliers[0].id,
    supplierName: demoSuppliers[0].name,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    status: "sent",
    orderDate: "2026-05-16",
    expectedDate: "2026-05-17",
    total: 2260,
    notes: "تأكيد السعر قبل الاستلام",
    items: [
      { itemId: "item-chicken", itemName: "دجاج", quantity: 100, expectedUnitPrice: 18, receivedQuantity: 0 },
      { itemId: "item-cheese", itemName: "جبنة", quantity: 200, expectedUnitPrice: 0.9, receivedQuantity: 0 },
    ],
  },
  {
    id: "PO-1008",
    organizationId: demoOrganization.id,
    supplierId: demoSuppliers[1].id,
    supplierName: demoSuppliers[1].name,
    branchId: demoBranches[1].id,
    branchName: demoBranches[1].name,
    status: "received",
    orderDate: "2026-05-14",
    expectedDate: "2026-05-15",
    total: 910,
    items: [
      { itemId: "item-rice", itemName: "أرز", quantity: 70, expectedUnitPrice: 6, receivedQuantity: 70 },
      { itemId: "item-potato", itemName: "بطاطا", quantity: 140, expectedUnitPrice: 3.5, receivedQuantity: 140 },
    ],
  },
];

export const demoInvoices: Invoice[] = [
  {
    id: "INV-771",
    organizationId: demoOrganization.id,
    supplierName: "مورد الدجاج",
    branchName: demoBranches[0].name,
    invoiceNumber: "D-2026-0441",
    status: "flagged",
    total: 2260,
    issuedAt: "2026-05-16",
  },
  {
    id: "INV-765",
    organizationId: demoOrganization.id,
    supplierName: "مورد الخضار",
    branchName: demoBranches[1].name,
    invoiceNumber: "V-2026-103",
    status: "paid",
    total: 910,
    issuedAt: "2026-05-15",
  },
];

export const demoCustomerInvoices: CustomerInvoice[] = [
  {
    id: "cinv-1001",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    invoiceNumber: "C-2026-1001",
    customerName: "عميل نقدي",
    customerPhone: "+970 599 777 111",
    status: "paid",
    paymentMethod: "cash",
    issuedAt: "2026-05-16T13:20:00Z",
    subtotal: 55,
    discount: 0,
    taxRate: 0,
    taxTotal: 0,
    total: 55,
    notes: "فاتورة مطبوعة من رواق",
    items: [
      { id: "cinv-1001-1", menuItemId: "menu-thai-chicken", name: "وجبة دجاج تايلندي", quantity: 1, unitPrice: 25, total: 25 },
      { id: "cinv-1001-2", menuItemId: "menu-zinger", name: "ساندويتش زنجر", quantity: 2, unitPrice: 15, total: 30 },
    ],
  },
  {
    id: "cinv-1002",
    organizationId: demoOrganization.id,
    branchId: demoBranches[1].id,
    branchName: demoBranches[1].name,
    invoiceNumber: "C-2026-1002",
    customerName: "شركة الرمال",
    customerPhone: "+970 599 888 222",
    customerTaxNumber: "562311204",
    status: "issued",
    paymentMethod: "card",
    issuedAt: "2026-05-16T15:45:00Z",
    subtotal: 84,
    discount: 4,
    taxRate: 0,
    taxTotal: 0,
    total: 80,
    items: [
      { id: "cinv-1002-1", menuItemId: "menu-veggie-rice", name: "أرز بالخضار", quantity: 3, unitPrice: 12, total: 36 },
      { id: "cinv-1002-2", menuItemId: "menu-thai-chicken", name: "وجبة دجاج تايلندي", quantity: 2, unitPrice: 25, total: 50 },
    ],
  },
];

export const demoCatalogItems: CatalogItem[] = [
  {
    id: "catalog-thai-chicken",
    organizationId: demoOrganization.id,
    code: "١٠٠١",
    name: "وجبة دجاج تايلندي",
    barcodes: ["٦٢٥١٠٠١٠٠١٠١", "٢١٠٠١"],
    categoryName: "وجبات",
    mainUnit: "وجبة",
    units: [
      { name: "وجبة", factor: 1, barcode: "٦٢٥١٠٠١٠٠١٠١" },
      { name: "عرض عائلي", factor: 4, barcode: "٢١٠٠١" },
    ],
    purchasePrice: 14,
    retailPrice: 25,
    wholesalePrice: 22,
    branchPrice: 24,
    customerPrice: 21,
    minimumQuantity: 20,
    taxRate: 0,
    isActive: true,
    stockQuantity: 86,
  },
  {
    id: "catalog-zinger",
    organizationId: demoOrganization.id,
    code: "١٠٠٢",
    name: "ساندويتش زنجر",
    barcodes: ["٦٢٥١٠٠١٠٠١٠٢", "٢١٠٠٢"],
    categoryName: "ساندويتش",
    mainUnit: "حبة",
    units: [
      { name: "حبة", factor: 1, barcode: "٦٢٥١٠٠١٠٠١٠٢" },
      { name: "كرتونة", factor: 24, barcode: "٢١٠٠٢" },
    ],
    purchasePrice: 8,
    retailPrice: 15,
    wholesalePrice: 13,
    minimumQuantity: 30,
    taxRate: 0,
    isActive: true,
    stockQuantity: 124,
  },
  {
    id: "catalog-rice",
    organizationId: demoOrganization.id,
    code: "٢٠٠١",
    name: "أرز بالخضار",
    barcodes: ["٦٢٥١٠٠١٠٠٢٠١"],
    categoryName: "أطباق جانبية",
    mainUnit: "طبق",
    units: [
      { name: "طبق", factor: 1, barcode: "٦٢٥١٠٠١٠٠٢٠١" },
      { name: "كيلو", factor: 3 },
    ],
    purchasePrice: 6,
    retailPrice: 12,
    wholesalePrice: 10,
    minimumQuantity: 25,
    taxRate: 0,
    isActive: true,
    stockQuantity: 67,
  },
  {
    id: "catalog-burger",
    organizationId: demoOrganization.id,
    code: "١٠٠٤",
    name: "برجر دجاج",
    barcodes: ["٦٢٥١٠٠١٠٠١٠٤"],
    categoryName: "برجر",
    mainUnit: "حبة",
    units: [
      { name: "حبة", factor: 1, barcode: "٦٢٥١٠٠١٠٠١٠٤" },
      { name: "كرتونة", factor: 12 },
    ],
    purchasePrice: 10,
    retailPrice: 18,
    wholesalePrice: 16,
    minimumQuantity: 18,
    taxRate: 0,
    isActive: true,
    stockQuantity: 42,
  },
];

export const demoSalesShift: SalesShift = {
  id: "shift-001",
  branchName: demoBranches[0].name,
  cashierName: "أحمد الكاشير",
  openedAt: "2026-05-16T08:00:00Z",
  openingCash: 500,
  cashSales: 1840,
  cardSales: 920,
  expenses: 120,
  withdrawals: 200,
  deposits: 100,
  expectedCash: 2120,
  actualCash: 2115,
  difference: -5,
  status: "open",
};

export const demoPermissionSettings = [
  { key: "edit_price", label: "تعديل السعر", roles: ["organization_owner", "branch_manager"] },
  { key: "apply_discount", label: "عمل خصم", roles: ["organization_owner", "branch_manager", "purchasing_manager"] },
  { key: "void_invoice", label: "إلغاء فاتورة", roles: ["organization_owner", "branch_manager"] },
  { key: "view_profit", label: "رؤية الأرباح", roles: ["organization_owner", "accountant"] },
  { key: "close_shift", label: "إغلاق الوردية", roles: ["organization_owner", "branch_manager", "accountant"] },
  { key: "edit_inventory", label: "تعديل المخزون", roles: ["organization_owner", "inventory_manager"] },
  { key: "delete_item", label: "حذف صنف", roles: ["organization_owner"] },
] satisfies import("@/types/domain").PermissionSetting[];

export const demoRestaurantTables: RestaurantTable[] = [
  {
    id: "table-1",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    number: 1,
    zone: "الصالة الرئيسية",
    seats: 4,
    status: "available",
    currentTotal: 0,
    orderItems: [],
  },
  {
    id: "table-2",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    number: 2,
    zone: "الصالة الرئيسية",
    seats: 6,
    status: "occupied",
    openedAt: "2026-05-16T18:10:00Z",
    waiterName: "سامي",
    guests: 4,
    currentTotal: 96,
    orderItems: [
      { name: "وجبة دجاج تايلندي", quantity: 2, total: 50 },
      { name: "ساندويتش زنجر", quantity: 2, total: 30 },
      { name: "أرز بالخضار", quantity: 1, total: 12 },
      { name: "مياه", quantity: 2, total: 4 },
    ],
  },
  {
    id: "table-3",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    number: 3,
    zone: "الصالة الرئيسية",
    seats: 2,
    status: "reserved",
    waiterName: "ليان",
    guests: 2,
    currentTotal: 0,
    orderItems: [],
  },
  {
    id: "table-4",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    number: 4,
    zone: "التراس",
    seats: 4,
    status: "occupied",
    openedAt: "2026-05-16T18:35:00Z",
    waiterName: "سامي",
    guests: 3,
    currentTotal: 58,
    orderItems: [
      { name: "برجر دجاج", quantity: 2, total: 36 },
      { name: "أرز بالخضار", quantity: 1, total: 12 },
      { name: "مشروبات", quantity: 2, total: 10 },
    ],
  },
  {
    id: "table-5",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    number: 5,
    zone: "التراس",
    seats: 4,
    status: "needs_cleaning",
    currentTotal: 0,
    orderItems: [],
  },
  {
    id: "table-6",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    number: 6,
    zone: "العائلات",
    seats: 8,
    status: "occupied",
    openedAt: "2026-05-16T19:05:00Z",
    waiterName: "ليان",
    guests: 6,
    currentTotal: 142,
    orderItems: [
      { name: "وجبة دجاج تايلندي", quantity: 3, total: 75 },
      { name: "ساندويتش زنجر", quantity: 2, total: 30 },
      { name: "برجر دجاج", quantity: 1, total: 18 },
      { name: "أرز بالخضار", quantity: 1, total: 12 },
      { name: "مياه", quantity: 3, total: 7 },
    ],
  },
  {
    id: "table-7",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    number: 7,
    zone: "العائلات",
    seats: 4,
    status: "available",
    currentTotal: 0,
    orderItems: [],
  },
  {
    id: "table-8",
    organizationId: demoOrganization.id,
    branchId: demoBranches[0].id,
    branchName: demoBranches[0].name,
    number: 8,
    zone: "العائلات",
    seats: 4,
    status: "available",
    currentTotal: 0,
    orderItems: [],
  },
];

export const demoPayableBills: PayableBill[] = [
  {
    id: "bill-electricity-1",
    organizationId: demoOrganization.id,
    billerName: "شركة توزيع الكهرباء",
    category: "كهرباء",
    billNumber: "كهرباء-٥٠١٢",
    referenceNumber: "مرجع-٢٠٢٦-٠٠١",
    dueDate: "2026-05-20",
    amount: 780,
    paidAmount: 0,
    remainingAmount: 780,
    status: "due",
    canPartialPay: true,
    lastInquiryAt: "2026-05-16T18:10:00Z",
  },
  {
    id: "bill-water-1",
    organizationId: demoOrganization.id,
    billerName: "بلدية غزة",
    category: "ماء",
    billNumber: "ماء-٣١٤٠",
    referenceNumber: "مرجع-٢٠٢٦-٠٠٢",
    dueDate: "2026-05-22",
    amount: 260,
    paidAmount: 100,
    remainingAmount: 160,
    status: "partial",
    canPartialPay: true,
    lastInquiryAt: "2026-05-16T18:11:00Z",
  },
  {
    id: "bill-internet-1",
    organizationId: demoOrganization.id,
    billerName: "مزود الإنترنت",
    category: "إنترنت",
    billNumber: "إنترنت-٩٠٢١",
    referenceNumber: "مرجع-٢٠٢٦-٠٠٣",
    dueDate: "2026-05-18",
    amount: 180,
    paidAmount: 0,
    remainingAmount: 180,
    status: "scheduled",
    canPartialPay: false,
    lastInquiryAt: "2026-05-16T18:12:00Z",
  },
  {
    id: "bill-rent-1",
    organizationId: demoOrganization.id,
    billerName: "إيجار الفرع",
    category: "إيجار",
    billNumber: "إيجار-الشهر",
    referenceNumber: "مرجع-٢٠٢٦-٠٠٤",
    dueDate: "2026-06-01",
    amount: 2200,
    paidAmount: 0,
    remainingAmount: 2200,
    status: "due",
    canPartialPay: true,
    lastInquiryAt: "2026-05-16T18:13:00Z",
  },
  {
    id: "bill-supplier-1",
    organizationId: demoOrganization.id,
    billerName: "مورد الدجاج",
    category: "مورد",
    billNumber: "فاتورة-توريد-٧٧١",
    referenceNumber: "مرجع-٢٠٢٦-٠٠٥",
    dueDate: "2026-05-17",
    amount: 2260,
    paidAmount: 0,
    remainingAmount: 2260,
    status: "overdue",
    canPartialPay: true,
    lastInquiryAt: "2026-05-16T18:14:00Z",
  },
];

export const demoBillPaymentBatches: BillPaymentBatch[] = [
  {
    id: "batch-1",
    organizationId: demoOrganization.id,
    referenceNumber: "دفعة-موحدة-١٠٠١",
    billIds: ["bill-electricity-1", "bill-water-1", "bill-internet-1"],
    totalAmount: 1120,
    status: "ready",
  },
  {
    id: "batch-2",
    organizationId: demoOrganization.id,
    referenceNumber: "دفعة-مجدولة-١٠٠٢",
    billIds: ["bill-rent-1"],
    totalAmount: 2200,
    scheduledFor: "2026-05-28",
    status: "scheduled",
  },
];

export const demoDirectDebitMandates: DirectDebitMandate[] = [
  {
    id: "mandate-1",
    organizationId: demoOrganization.id,
    customerName: "مطعم إيوان",
    billerName: "شركة توزيع الكهرباء",
    accountHint: "حساب ينتهي بـ ٢٣٤٥",
    amountLimit: 1200,
    nextDueDate: "2026-06-20",
    status: "active",
    activatedAt: "2026-05-01T10:00:00Z",
    lastPaymentAt: "2026-05-20T09:00:00Z",
    channel: "بوابة دفع",
  },
  {
    id: "mandate-2",
    organizationId: demoOrganization.id,
    customerName: "مطعم إيوان",
    billerName: "مزود الإنترنت",
    accountHint: "بطاقة تنتهي بـ ٨٨١٢",
    amountLimit: 250,
    nextDueDate: "2026-06-18",
    status: "active",
    activatedAt: "2026-05-03T12:00:00Z",
    lastPaymentAt: "2026-05-18T09:10:00Z",
    channel: "تطبيق",
  },
  {
    id: "mandate-3",
    organizationId: demoOrganization.id,
    customerName: "مطعم إيوان",
    billerName: "بلدية غزة",
    accountHint: "حساب ينتهي بـ ٧٠١١",
    amountLimit: 400,
    nextDueDate: "2026-06-22",
    status: "paused",
    activatedAt: "2026-04-28T08:30:00Z",
    channel: "حساب بنكي",
  },
];

export const demoDirectDebitRuns: DirectDebitRun[] = [
  {
    id: "run-1",
    mandateId: "mandate-1",
    billerName: "شركة توزيع الكهرباء",
    customerName: "مطعم إيوان",
    dueDate: "2026-06-20",
    amount: 830,
    status: "scheduled",
    message: "سيتم الخصم تلقائيًا في تاريخ الاستحقاق",
  },
  {
    id: "run-2",
    mandateId: "mandate-2",
    billerName: "مزود الإنترنت",
    customerName: "مطعم إيوان",
    dueDate: "2026-06-18",
    amount: 180,
    status: "paid",
    message: "تم الدفع بنجاح خلال آخر دورة",
  },
  {
    id: "run-3",
    mandateId: "mandate-3",
    billerName: "بلدية غزة",
    customerName: "مطعم إيوان",
    dueDate: "2026-06-22",
    amount: 210,
    status: "failed",
    message: "التفويض متوقف مؤقتًا",
  },
];

export const demoSmartSavingsFeatures: SmartSavingsFeature[] = [
  {
    id: "mobile-scanner",
    title: "الجوال ماسح باركود",
    description: "استخدام كاميرا الجوال لمسح المنتج وإضافته للفاتورة دون شراء جهاز ماسح منفصل.",
    monthlySaving: 180,
    status: "active",
  },
  {
    id: "digital-receipts",
    title: "فاتورة رقمية بدون ورق",
    description: "إظهار رمز استجابة للزبون لتنزيل الفاتورة على جواله بدل الطباعة الورقية.",
    monthlySaving: 240,
    status: "active",
  },
  {
    id: "remote-management",
    title: "إدارة من أي مكان",
    description: "متابعة المبيعات والفروع والفواتير من البيت أو الطريق عبر لوحة تحكم سحابية.",
    monthlySaving: 320,
    status: "available",
  },
  {
    id: "device-light",
    title: "تشغيل بتجهيزات أقل",
    description: "تقليل الاعتماد على أجهزة باركود وطابعات وصيانة مستمرة، مع بقاء البيع سريعًا.",
    monthlySaving: 210,
    status: "active",
  },
];

export const demoDigitalReceiptShares: DigitalReceiptShare[] = [
  {
    invoiceNumber: "فاتورة-٢٠٢٦٠٥-١٩١٥",
    customerName: "عميل نقدي",
    total: 55,
    receiptUrl: "https://rewaq.app/r/202605-1915",
    sentAt: "2026-05-16T19:15:00Z",
    status: "viewed",
  },
  {
    invoiceNumber: "فاتورة-٢٠٢٦٠٥-١٩٢٠",
    customerName: "طاولة ٦",
    total: 142,
    receiptUrl: "https://rewaq.app/r/202605-1920",
    sentAt: "2026-05-16T19:20:00Z",
    status: "ready",
  },
  {
    invoiceNumber: "فاتورة-٢٠٢٦٠٥-١٩٢٨",
    customerName: "شركة الرمال",
    total: 80,
    receiptUrl: "https://rewaq.app/r/202605-1928",
    sentAt: "2026-05-16T19:28:00Z",
    status: "sent",
  },
];

const financialCalendarSeed = [
  [1, 1680, 1180],
  [2, 2140, 1390],
  [3, 1890, 2030],
  [4, 2410, 1515],
  [5, 1320, 1195],
  [6, 2650, 1580],
  [7, 2280, 1460],
  [8, 1745, 1125],
  [9, 1980, 1240],
  [10, 3120, 1850],
  [11, 2860, 1760],
  [12, 1550, 1610],
  [13, 2070, 1280],
  [14, 2360, 1490],
  [15, 2580, 1675],
  [16, 3010, 1880],
] as const;

export const demoFinancialCalendar: FinancialCalendarDay[] = financialCalendarSeed.map(([day, salesTotal, expensesTotal]) => {
  const netProfit = salesTotal - expensesTotal;
  const date = `2026-05-${String(day).padStart(2, "0")}`;
  return {
    date,
    branchName: day % 2 === 0 ? demoBranches[0].name : demoBranches[1].name,
    salesTotal,
    expensesTotal,
    netProfit,
    cashSales: Math.round(salesTotal * 0.62),
    cardSales: Math.round(salesTotal * 0.38),
    status: netProfit > 80 ? "profit" : netProfit < 0 ? "loss" : "balanced",
    sales: [
      { itemName: "وجبة دجاج تايلندي", quantity: 18 + day, revenue: Math.round(salesTotal * 0.42) },
      { itemName: "ساندويتش زنجر", quantity: 12 + day, revenue: Math.round(salesTotal * 0.28) },
      { itemName: "أرز بالخضار", quantity: 8 + day, revenue: Math.round(salesTotal * 0.16) },
      { itemName: "برجر دجاج", quantity: 6 + day, revenue: Math.round(salesTotal * 0.14) },
    ],
    expenses: [
      { category: "أجور", amount: Math.round(expensesTotal * 0.28), notes: "تكلفة العمالة اليومية" },
      { category: "مواد خام", amount: Math.round(expensesTotal * 0.48), notes: "مكونات مستهلكة من الوصفات" },
      { category: "كهرباء وماء", amount: Math.round(expensesTotal * 0.08), notes: "توزيع يومي من الفاتورة الشهرية" },
      { category: "إيجار", amount: Math.round(expensesTotal * 0.1), notes: "حصة اليوم من الإيجار" },
      { category: "مصروفات أخرى", amount: Math.round(expensesTotal * 0.06), notes: "تنظيف وتغليف ومصاريف تشغيل" },
    ],
  };
});

export const demoCostTracking: CostTrackingData = {
  date: "2026-05-16",
  branchName: demoBranches[0].name,
  salesTotal: 5000,
  expensesTotal: 2510,
  netProfit: 2490,
  profitMarginPercent: 49.8,
  sections: [
    {
      id: "raw-materials",
      title: "المواد الخام",
      description: "تكلفة المكونات التي خرجت من المخزون بسبب البيع الفعلي.",
      total: 1800,
      lines: [
        { name: "دجاج", amount: 900, quantity: 52.3, unit: "كغم", notes: "أعلى مادة مستهلكة اليوم" },
        { name: "خبز", amount: 200, quantity: 286, unit: "قطعة" },
        { name: "بطاطا", amount: 180, quantity: 24, unit: "كغم" },
        { name: "صوصات", amount: 120, quantity: 3400, unit: "مل" },
        { name: "مشروبات", amount: 250, quantity: 116, unit: "عبوة" },
        { name: "حلويات", amount: 150, quantity: 30, unit: "قطعة" },
      ],
    },
    {
      id: "labor",
      title: "الرواتب اليومية",
      description: "تكلفة الأشخاص الموجودين في الوردية لهذا اليوم.",
      total: 330,
      lines: [
        { name: "شيف 1", amount: 70 },
        { name: "شيف 2", amount: 70 },
        { name: "كاشير", amount: 50 },
        { name: "جرسون 1", amount: 50 },
        { name: "جرسون 2", amount: 50 },
        { name: "تنظيف", amount: 40 },
      ],
    },
    {
      id: "operations",
      title: "المصاريف التشغيلية",
      description: "كل شيء يستهلك لتشغيل اليوم وليس مادة مباشرة في الطبق.",
      total: 170,
      lines: [
        { name: "كهرباء", amount: 50 },
        { name: "غاز", amount: 40 },
        { name: "ماء", amount: 10 },
        { name: "إنترنت", amount: 5 },
        { name: "أكياس وتغليف", amount: 45 },
        { name: "منظفات", amount: 20 },
      ],
    },
    {
      id: "fixed",
      title: "المصاريف الثابتة اليومية",
      description: "تحويل المصاريف الشهرية إلى تكلفة يومية على أساس 30 يومًا.",
      total: 130,
      lines: [
        { name: "إيجار", amount: 100, notes: "3000 شيكل شهريًا ÷ 30" },
        { name: "صيانة", amount: 20, notes: "600 شيكل شهريًا ÷ 30" },
        { name: "اشتراك نظام الكاش", amount: 10, notes: "300 شيكل شهريًا ÷ 30" },
      ],
    },
    {
      id: "waste",
      title: "الهدر والتالف",
      description: "المواد التي خرجت من المخزون بدون بيع وربح.",
      total: 80,
      lines: [
        { name: "دجاج مرمي", amount: 50, quantity: 2.9, unit: "كغم", notes: "تلف قبل التحضير" },
        { name: "بطاطا محروقة", amount: 20, quantity: 2.7, unit: "كغم" },
        { name: "مشروب منسكب", amount: 10, quantity: 5, unit: "عبوات" },
      ],
    },
  ],
  costCenters: [
    { name: "المواد الخام", amount: 1800, percent: 36, status: "watch", notes: "الدجاج وحده يمثل نصف تكلفة المواد تقريبًا" },
    { name: "الرواتب", amount: 330, percent: 6.6, status: "healthy", notes: "ضمن النطاق الصحي لهذا اليوم" },
    { name: "التشغيل", amount: 170, percent: 3.4, status: "healthy", notes: "راقب التغليف لأنه يرتفع مع الدليفري" },
    { name: "الثابت اليومي", amount: 130, percent: 2.6, status: "healthy", notes: "محسوب من المصاريف الشهرية" },
    { name: "الهدر", amount: 80, percent: 1.6, status: "danger", notes: "الدجاج المرمي أخطر بند هدر اليوم" },
  ],
  channelBreakdown: [
    { channel: "الصالة", orders: 96, revenue: 2900, directCost: 1180, profit: 1720 },
    { channel: "الدليفري", orders: 48, revenue: 1550, directCost: 820, profit: 730 },
    { channel: "الاستلام", orders: 22, revenue: 550, directCost: 220, profit: 330 },
  ],
  smartInsights: [
    { title: "أكثر مادة استهلاكًا", value: "دجاج 40٪", notes: "راقب سعر المورد وكمية الهدر يوميًا", tone: "warning" },
    { title: "أعلى هدر", value: "دجاج مرمي", notes: "50 شيكل خرجت بلا مبيعات", tone: "danger" },
    { title: "أكثر موظف تكلفة", value: "الشيفات", notes: "140 شيكل من وردية اليوم", tone: "default" },
    { title: "تكلفة التغليف", value: "45 شيكل", notes: "مرتبطة مباشرة بطلبات الدليفري", tone: "warning" },
  ],
};

export const demoRecipes: Recipe[] = [
  {
    id: "recipe-thai-chicken",
    organizationId: demoOrganization.id,
    name: "وجبة دجاج تايلندي",
    category: "وجبات",
    servings: 1,
    preparation: "تشويح الدجاج مع الصوص الحار وتقديمه مع الأرز.",
    ingredients: [
      { itemId: "item-chicken", itemName: "دجاج", quantity: 0.22, unit: "كغم", unitCost: 17.2, totalCost: 3.78 },
      { itemId: "item-rice", itemName: "أرز", quantity: 0.18, unit: "كغم", unitCost: 5.7, totalCost: 1.03 },
      { itemId: "item-hot-sauce", itemName: "صوص حار", quantity: 40, unit: "مل", unitCost: 0.038, totalCost: 1.52 },
      { itemId: "item-packaging", itemName: "علب تغليف", quantity: 1, unit: "قطعة", unitCost: 0.33, totalCost: 0.33 },
    ],
    totalCost: 6.66,
    costPerServing: 6.66,
    status: "active",
  },
  {
    id: "recipe-zinger",
    organizationId: demoOrganization.id,
    name: "ساندويتش زنجر",
    category: "ساندويتش",
    servings: 1,
    ingredients: [
      { itemId: "item-chicken", itemName: "دجاج", quantity: 0.16, unit: "كغم", unitCost: 17.2, totalCost: 2.75 },
      { itemId: "item-bun", itemName: "خبز برجر", quantity: 1, unit: "قطعة", unitCost: 0.72, totalCost: 0.72 },
      { itemId: "item-cheese", itemName: "جبنة", quantity: 1, unit: "شريحة", unitCost: 0.84, totalCost: 0.84 },
      { itemId: "item-hot-sauce", itemName: "صوص حار", quantity: 25, unit: "مل", unitCost: 0.038, totalCost: 0.95 },
    ],
    totalCost: 5.26,
    costPerServing: 5.26,
    status: "active",
  },
  {
    id: "recipe-veggie-rice",
    organizationId: demoOrganization.id,
    name: "أرز بالخضار",
    category: "أطباق جانبية",
    servings: 1,
    ingredients: [
      { itemId: "item-rice", itemName: "أرز", quantity: 0.2, unit: "كغم", unitCost: 5.7, totalCost: 1.14 },
      { itemId: "item-oil", itemName: "زيت", quantity: 0.04, unit: "لتر", unitCost: 8.6, totalCost: 0.34 },
      { itemId: "item-packaging", itemName: "علب تغليف", quantity: 1, unit: "قطعة", unitCost: 0.33, totalCost: 0.33 },
    ],
    totalCost: 1.81,
    costPerServing: 1.81,
    status: "active",
  },
  {
    id: "recipe-chicken-burger",
    organizationId: demoOrganization.id,
    name: "برجر دجاج",
    category: "برجر",
    servings: 1,
    ingredients: [
      { itemId: "item-chicken", itemName: "دجاج", quantity: 0.18, unit: "كغم", unitCost: 17.2, totalCost: 3.1 },
      { itemId: "item-bun", itemName: "خبز برجر", quantity: 1, unit: "قطعة", unitCost: 0.72, totalCost: 0.72 },
      { itemId: "item-cheese", itemName: "جبنة", quantity: 1, unit: "شريحة", unitCost: 0.84, totalCost: 0.84 },
    ],
    totalCost: 4.66,
    costPerServing: 4.66,
    status: "active",
  },
];

export const demoMenuItems: MenuItem[] = [
  {
    id: "menu-thai-chicken",
    organizationId: demoOrganization.id,
    name: "وجبة دجاج تايلندي",
    recipeId: "recipe-thai-chicken",
    recipeName: "وجبة دجاج تايلندي",
    sellingPrice: 25,
    recipeCost: 6.66,
    grossProfit: 18.34,
    foodCostPercent: 26.6,
    profitMarginPercent: 73.4,
    status: "active",
  },
  {
    id: "menu-zinger",
    organizationId: demoOrganization.id,
    name: "ساندويتش زنجر",
    recipeId: "recipe-zinger",
    recipeName: "ساندويتش زنجر",
    sellingPrice: 15,
    recipeCost: 5.26,
    grossProfit: 9.74,
    foodCostPercent: 35.1,
    profitMarginPercent: 64.9,
    status: "active",
  },
  {
    id: "menu-veggie-rice",
    organizationId: demoOrganization.id,
    name: "أرز بالخضار",
    recipeId: "recipe-veggie-rice",
    recipeName: "أرز بالخضار",
    sellingPrice: 12,
    recipeCost: 1.81,
    grossProfit: 10.19,
    foodCostPercent: 15.1,
    profitMarginPercent: 84.9,
    status: "active",
  },
  {
    id: "menu-chicken-burger",
    organizationId: demoOrganization.id,
    name: "برجر دجاج",
    recipeId: "recipe-chicken-burger",
    recipeName: "برجر دجاج",
    sellingPrice: 18,
    recipeCost: 4.66,
    grossProfit: 13.34,
    foodCostPercent: 25.9,
    profitMarginPercent: 74.1,
    status: "active",
  },
];

export const demoWasteLogs: WasteLog[] = [
  {
    id: "WST-204",
    organizationId: demoOrganization.id,
    branchName: demoBranches[0].name,
    itemName: "زيت",
    quantity: 4,
    reason: "كسر/انسكاب",
    cost: 34.4,
    loggedAt: "2026-05-15",
    notes: "تسرب من عبوة مفتوحة",
  },
  {
    id: "WST-205",
    organizationId: demoOrganization.id,
    branchName: demoBranches[1].name,
    itemName: "خبز برجر",
    quantity: 18,
    reason: "انتهاء صلاحية",
    cost: 12.96,
    loggedAt: "2026-05-16",
  },
];

export const demoTransfers: Transfer[] = [
  {
    id: "TR-044",
    organizationId: demoOrganization.id,
    fromBranchName: demoBranches[0].name,
    toBranchName: demoBranches[1].name,
    status: "received",
    createdAt: "2026-05-14",
    totalItems: 2,
  },
  {
    id: "TR-045",
    organizationId: demoOrganization.id,
    fromBranchName: demoBranches[1].name,
    toBranchName: demoBranches[0].name,
    status: "sent",
    createdAt: "2026-05-16",
    totalItems: 1,
  },
];

export const demoSocialAccounts: SocialAccount[] = [
  {
    id: "soc-fb",
    organizationId: demoOrganization.id,
    platform: "facebook",
    accountName: "مطعم إيوان - فيسبوك",
    status: "connected",
    lastPublishedAt: "2026-05-15T18:00:00Z",
  },
  {
    id: "soc-ig",
    organizationId: demoOrganization.id,
    platform: "instagram",
    accountName: "iwan.restaurant",
    status: "connected",
    lastPublishedAt: "2026-05-16T08:20:00Z",
  },
  {
    id: "soc-wa",
    organizationId: demoOrganization.id,
    platform: "whatsapp",
    accountName: "قناة واتساب إيوان",
    status: "connected",
    lastPublishedAt: "2026-05-16T08:25:00Z",
  },
  {
    id: "soc-tg",
    organizationId: demoOrganization.id,
    platform: "telegram",
    accountName: "قناة عروض إيوان",
    status: "connected",
    lastPublishedAt: "2026-05-16T08:30:00Z",
  },
  {
    id: "soc-tt",
    organizationId: demoOrganization.id,
    platform: "tiktok",
    accountName: "iwan.kitchen",
    status: "connected",
    lastPublishedAt: "2026-05-14T17:45:00Z",
  },
  {
    id: "soc-x",
    organizationId: demoOrganization.id,
    platform: "x",
    accountName: "@iwan_restaurant",
    status: "connected",
    lastPublishedAt: "2026-05-15T09:15:00Z",
  },
  {
    id: "soc-gbp",
    organizationId: demoOrganization.id,
    platform: "google_business",
    accountName: "مطعم إيوان على Google",
    status: "connected",
    lastPublishedAt: "2026-05-13T12:00:00Z",
  },
  {
    id: "soc-li",
    organizationId: demoOrganization.id,
    platform: "linkedin",
    accountName: "Rewaq Restaurant Group",
    status: "connected",
    lastPublishedAt: "2026-05-12T10:00:00Z",
  },
  {
    id: "soc-yt",
    organizationId: demoOrganization.id,
    platform: "youtube_shorts",
    accountName: "Thai Kitchen Shorts",
    status: "connected",
    lastPublishedAt: "2026-05-11T18:30:00Z",
  },
  {
    id: "soc-pin",
    organizationId: demoOrganization.id,
    platform: "pinterest",
    accountName: "Thai Restaurant Boards",
    status: "connected",
    lastPublishedAt: "2026-05-10T16:00:00Z",
  },
];

export const demoSocialTemplates: SocialTemplate[] = [
  {
    id: "tpl-today",
    organizationId: demoOrganization.id,
    name: "عرض اليوم",
    category: "promotion",
    body: "عرض اليوم من رواق: {dish} بسعر خاص حتى نهاية الدوام. اطلبها الآن من أقرب فرع.",
  },
  {
    id: "tpl-new-dish",
    organizationId: demoOrganization.id,
    name: "طبق جديد",
    category: "menu",
    body: "جديدنا اليوم: {dish}. وصفة طازجة بطعم مختلف وتجربة تستحق المشاركة.",
  },
  {
    id: "tpl-weekend",
    organizationId: demoOrganization.id,
    name: "خصم نهاية الأسبوع",
    category: "promotion",
    body: "نهاية الأسبوع ألذ مع خصم خاص على وجبات مختارة في كل الفروع.",
  },
  {
    id: "tpl-branch",
    organizationId: demoOrganization.id,
    name: "افتتاح فرع",
    category: "branch",
    body: "افتتحنا فرعنا الجديد لخدمتكم بشكل أسرع. ننتظركم اليوم.",
  },
  {
    id: "tpl-limited",
    organizationId: demoOrganization.id,
    name: "وجبة محدودة",
    category: "limited",
    body: "لفترة محدودة فقط: {dish}. الكمية محدودة والحجز متاح الآن.",
  },
  {
    id: "tpl-ramadan",
    organizationId: demoOrganization.id,
    name: "تنبيه دوام رمضان",
    category: "hours",
    body: "مواعيد دوام رمضان: نستقبلكم يوميًا من بعد الإفطار وحتى السحور.",
  },
  {
    id: "tpl-out",
    organizationId: demoOrganization.id,
    name: "نفاد صنف مؤقت",
    category: "notice",
    body: "نعتذر منكم، {dish} غير متاح مؤقتًا وسنعلِمكم عند عودته للقائمة.",
  },
];

export const demoSocialPosts: SocialPost[] = [
  {
    id: "post-501",
    organizationId: demoOrganization.id,
    title: "عرض وجبة دجاج تايلندي",
    body: "وجبة دجاج تايلندي اليوم بسعر خاص. متاحة في فرعي الرمال وشارع عبد القادر الحسيني.",
    status: "published",
    targets: [
      { platform: "facebook", accountName: "مطعم إيوان - فيسبوك", status: "published" },
      { platform: "instagram", accountName: "iwan.restaurant", status: "published" },
      { platform: "telegram", accountName: "قناة عروض إيوان", status: "published" },
      { platform: "google_business", accountName: "مطعم إيوان على Google", status: "published" },
      { platform: "linkedin", accountName: "Rewaq Restaurant Group", status: "published" },
    ],
    createdAt: "2026-05-15T18:00:00Z",
  },
  {
    id: "post-502",
    organizationId: demoOrganization.id,
    title: "خصم نهاية الأسبوع",
    body: "خصم 15% على ساندويتش زنجر حتى السبت.",
    status: "scheduled",
    scheduledAt: "2026-05-16T20:00:00Z",
    targets: [
      { platform: "facebook", accountName: "مطعم إيوان - فيسبوك", status: "pending" },
      { platform: "instagram", accountName: "iwan.restaurant", status: "pending" },
      { platform: "telegram", accountName: "قناة عروض إيوان", status: "pending" },
      { platform: "tiktok", accountName: "iwan.kitchen", status: "pending" },
      { platform: "x", accountName: "@iwan_restaurant", status: "pending" },
      { platform: "youtube_shorts", accountName: "Thai Kitchen Shorts", status: "pending" },
      { platform: "pinterest", accountName: "Thai Restaurant Boards", status: "pending" },
    ],
    createdAt: "2026-05-16T10:00:00Z",
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "notif-1",
    organizationId: demoOrganization.id,
    type: "low_stock",
    title: "دجاج وصل للحد الأدنى",
    body: "فرع شارع عبد القادر الحسيني لديه 32 كغم فقط من الدجاج.",
    severity: "warning",
    createdAt: "2026-05-16T08:00:00Z",
  },
  {
    id: "notif-2",
    organizationId: demoOrganization.id,
    type: "price_increase",
    title: "ارتفاع سعر الدجاج",
    body: "سعر الدجاج ارتفع 18% عن آخر شراء.",
    severity: "danger",
    createdAt: "2026-05-16T09:15:00Z",
  },
  {
    id: "notif-3",
    organizationId: demoOrganization.id,
    type: "high_food_cost",
    title: "وصفة تحتاج مراجعة",
    body: "ساندويتش زنجر تجاوز نسبة تكلفة الطعام 35%.",
    severity: "warning",
    createdAt: "2026-05-16T11:45:00Z",
  },
  {
    id: "notif-4",
    organizationId: demoOrganization.id,
    type: "publish_failed",
    title: "تعذر النشر على إنستغرام",
    body: "منشور عرض دجاج تايلندي نُشر على فيسبوك وتلغرام وفشل على إنستغرام.",
    severity: "danger",
    createdAt: "2026-05-15T18:02:00Z",
  },
];

export const demoDashboard: DashboardData = {
  salesEstimate: 18450,
  inventoryValue: 42800,
  lowStockCount: 3,
  openPurchaseOrders: 4,
  foodCostPercent: 29.8,
  highCostRecipes: demoRecipes.filter((recipe) => recipe.totalCost > 5),
  alerts: demoNotifications,
  inventoryByCategory: [
    { label: "بروتين", value: 15400 },
    { label: "نشويات", value: 8200 },
    { label: "زيوت", value: 5100 },
    { label: "صوصات", value: 2700 },
    { label: "تغليف", value: 4100 },
  ],
  purchaseCost30Days: [
    { label: "17 أبريل", value: 1200 },
    { label: "24 أبريل", value: 2100 },
    { label: "1 مايو", value: 1800 },
    { label: "8 مايو", value: 3200 },
    { label: "15 مايو", value: 2260 },
  ],
  foodCostTrend: [
    { label: "الأسبوع 1", value: 31 },
    { label: "الأسبوع 2", value: 28 },
    { label: "الأسبوع 3", value: 29.5 },
    { label: "الأسبوع 4", value: 29.8 },
  ],
  wasteByBranch: [
    { label: "عبد القادر الحسيني", value: 410 },
    { label: "الرمال", value: 260 },
  ],
};

export const demoAdminMetrics: AdminMetric[] = [
  { label: "المؤسسات النشطة", value: "24", delta: "+3 هذا الشهر", tone: "success" },
  { label: "إيراد شهري متكرر", value: "₪18,900", delta: "+12%", tone: "success" },
  { label: "طلبات دعم مفتوحة", value: "7", delta: "2 عالية الأولوية", tone: "warning" },
  { label: "وظائف نشر فاشلة", value: "5", delta: "آخر 24 ساعة", tone: "danger" },
];

export const demoSystemLogs = [
  { id: "log-1", level: "warning", message: "انتهت صلاحية ربط حساب إنستغرام", createdAt: "2026-05-16 10:22" },
  { id: "log-2", level: "info", message: "تم استلام طلب شراء وتسجيل حركات المخزون", createdAt: "2026-05-15 15:12" },
  { id: "log-3", level: "error", message: "فشل النشر التجريبي على إنستغرام", createdAt: "2026-05-15 18:02" },
];
