import {
  BarChart3,
  Barcode,
  Bell,
  Boxes,
  Building2,
  Calculator,
  ChefHat,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  FileText,
  Factory,
  Gauge,
  Landmark,
  LayoutGrid,
  ListChecks,
  Megaphone,
  MonitorSmartphone,
  PackageMinus,
  PiggyBank,
  ReceiptText,
  RotateCcw,
  Settings,
  Shield,
  SlidersHorizontal,
  Store,
  Timer,
  Truck,
  UserCheck,
  Users,
  UtensilsCrossed,
  WalletCards,
  Tablet,
  Warehouse,
  Scale,
  BookOpenCheck,
  FileSpreadsheet,
  Coins,
  Calendar,
} from "lucide-react";

export const appNav = [
  {
    title: "التشغيل اليومي",
    items: [
      { title: "لوحة التحكم", href: "/dashboard", icon: Gauge },
      { title: "شاشة الكاشير POS", href: "/d/pos", icon: MonitorSmartphone },
      { title: "شاشة المطبخ KDS", href: "/d/kitchen", icon: ChefHat },
      { title: "الورديات والصندوق", href: "/dashboard/shifts", icon: Timer },
      { title: "إدارة الطاولات", href: "/dashboard/tables", icon: LayoutGrid },
    ],
  },
  {
    title: "المبيعات والعملاء",
    items: [
      { title: "فواتير العملاء", href: "/dashboard/customer-invoices", icon: ReceiptText },
      { title: "العملاء والذمم", href: "/dashboard/customers", icon: Users },
      { title: "مرتجعات المبيعات", href: "/dashboard/sales-returns", icon: RotateCcw },
      { title: "أطباق القائمة", href: "/dashboard/menu-items", icon: UtensilsCrossed },
      { title: "مجموعات الإضافات", href: "/dashboard/modifiers", icon: SlidersHorizontal },
    ],
  },
  {
    title: "المخزون",
    items: [
      { title: "مخطط المخزن (المخزون)", href: "/dashboard/inventory", icon: Boxes },
      { title: "المستودع العام", href: "/dashboard/inventory?warehouse=general", icon: Warehouse },
      { title: "مستودع المطبخ", href: "/dashboard/inventory?warehouse=kitchen", icon: ChefHat },
      { title: "الأصناف / المواد", href: "/dashboard/items", icon: Barcode },
      { title: "حركات المخزن", href: "/dashboard/stock-movements", icon: FileText },
      { title: "الجرد", href: "/dashboard/stock-counts", icon: ListChecks },
      { title: "التحويلات الداخلية", href: "/dashboard/transfers", icon: Truck },
      { title: "التالف والمحاريق", href: "/dashboard/waste", icon: PackageMinus },
    ],
  },
  {
    title: "المشتريات والموردون",
    items: [
      { title: "الموردون", href: "/dashboard/suppliers", icon: Store },
      { title: "فواتير التوريد", href: "/dashboard/invoices", icon: ReceiptText },
      { title: "طلبيات الأقسام", href: "/dashboard/purchase-orders", icon: ClipboardCheck },
    ],
  },
  {
    title: "المطبخ والتكاليف",
    items: [
      { title: "الوصفات وكروت الإنتاج", href: "/dashboard/recipes", icon: ChefHat },
      { title: "أوامر الإنتاج وصرف المطبخ", href: "/dashboard/production", icon: Factory },
      { title: "محاسبة التكاليف والريسبي", href: "/dashboard/cost-accounting", icon: Calculator },
      { title: "تحليل تكلفة الطعام", href: "/dashboard/food-cost", icon: BarChart3 },
    ],
  },
  {
    title: "التقارير والتسويق",
    items: [
      { title: "تقارير المخزن", href: "/dashboard/reports", icon: BarChart3 },
      { title: "تقرير تذبذب الأسعار", href: "/dashboard/reports?type=price_changes", icon: BarChart3 },
      { title: "النشر عبر السوشيال ميديا", href: "/dashboard/social-publishing", icon: Megaphone },
      { title: "إدارة التسويق", href: "/dashboard/marketing", icon: ClipboardList },
    ],
  },
  {
    title: "الخدمات المالية",
    items: [
      { title: "أموالي", href: "/dashboard/amwali", icon: Coins },
      { title: "دفع الفواتير", href: "/dashboard/bill-payments", icon: CreditCard },
      { title: "الخصم المباشر", href: "/dashboard/direct-debit", icon: Landmark },
      { title: "التوفير الذكي", href: "/dashboard/smart-savings", icon: PiggyBank },
      { title: "التقويم المالي", href: "/dashboard/financial-calendar", icon: Calendar },
    ],
  },
  {
    title: "الإعدادات",
    items: [
      { title: "الفروع", href: "/dashboard/branches", icon: Building2 },
      { title: "المستخدمون والفريق", href: "/dashboard/settings/users", icon: UserCheck },
      { title: "تخصيص الأجهزة والأكواد", href: "/dashboard/settings/devices", icon: Tablet },
      { title: "الإعدادات / الأقسام", href: "/dashboard/settings", icon: Settings },
      { title: "الفوترة والاشتراك", href: "/dashboard/billing", icon: WalletCards },
    ],
  },
];

export const accountingNav = {
  title: "المحاسبة",
  items: [
    { title: "لوحة المحاسبة", href: "/dashboard/accounting", icon: Gauge, roles: ["super_admin", "organization_owner", "accountant", "branch_manager"] },
    { title: "دليل الحسابات", href: "/dashboard/accounting/accounts", icon: BookOpenCheck, roles: ["super_admin", "organization_owner", "accountant"] },
    { title: "دفتر الأستاذ", href: "/dashboard/accounting/ledger", icon: Scale, roles: ["super_admin", "organization_owner", "accountant"] },
    { title: "ميزان المراجعة", href: "/dashboard/accounting/trial-balance", icon: FileSpreadsheet, roles: ["super_admin", "organization_owner", "accountant"] },
    { title: "المصروفات", href: "/dashboard/accounting/expenses", icon: WalletCards, roles: ["super_admin", "organization_owner", "accountant", "branch_manager"] },
    { title: "مراكز التكلفة", href: "/dashboard/accounting/cost-centers", icon: Coins, roles: ["super_admin", "organization_owner", "accountant"] },
    { title: "الإقفال الشهري", href: "/dashboard/accounting/closing", icon: Calendar, roles: ["super_admin", "organization_owner", "accountant"] },
    { title: "إعدادات المحاسبة", href: "/dashboard/accounting/settings", icon: Settings, roles: ["super_admin", "organization_owner"] },
  ],
};

export const adminNav = [
  { title: "لوحة الأدمن", href: "/admin", icon: Shield },
  { title: "طلبات التسجيل", href: "/admin/account-requests", icon: UserCheck },
  { title: "المؤسسات", href: "/admin/organizations", icon: Building2 },
  { title: "المستخدمون", href: "/admin/users", icon: Users },
  { title: "الخطط", href: "/admin/plans", icon: WalletCards },
  { title: "مفاتيح الميزات", href: "/admin/feature-flags", icon: Settings },
  { title: "سجلات النظام", href: "/admin/system-logs", icon: FileText },
  { title: "تذاكر الدعم", href: "/admin/support-tickets", icon: Bell },
];
