import {
  BarChart3,
  Barcode,
  Bell,
  Boxes,
  Building2,
  Calculator,
  ChefHat,
  ClipboardCheck,
  FileText,
  Factory,
  Gauge,
  MonitorSmartphone,
  PackageMinus,
  ReceiptText,
  RotateCcw,
  Settings,
  Shield,
  Store,
  Truck,
  UserCheck,
  Users,
  WalletCards,
  Tablet,
  Warehouse,
  Scale,
} from "lucide-react";

export const appNav = [
  {
    title: "نظام المطاعم",
    items: [
      { title: "محاسبة التكاليف والريسبي", href: "/dashboard/cost-accounting", icon: Calculator },
      { title: "تحليل تكلفة الطعام", href: "/dashboard/food-cost", icon: BarChart3 },
      { title: "دفتر الأستاذ والقيود", href: "/dashboard/accounting/ledger", icon: Scale },
      { title: "الوصفات وكروت الإنتاج", href: "/dashboard/recipes", icon: ChefHat },
      { title: "أوامر الإنتاج وصرف المطبخ", href: "/dashboard/production", icon: Factory },
      { title: "شاشة الكاشير POS", href: "/d/pos", icon: MonitorSmartphone },
    ],
  },
  {
    title: "إدارة المخزن",
    items: [
      { title: "لوحة المخزن", href: "/dashboard", icon: Gauge },
      { title: "مخطط المخزن (المخزون)", href: "/dashboard/inventory", icon: Boxes },
      { title: "المستودع العام", href: "/dashboard/inventory?warehouse=general", icon: Warehouse },
      { title: "مستودع المطبخ", href: "/dashboard/inventory?warehouse=kitchen", icon: ChefHat },
      { title: "حركات المخزن (الصادر والوارد)", href: "/dashboard/stock-movements", icon: FileText },
      { title: "الأصناف / المواد", href: "/dashboard/items", icon: Barcode },
      { title: "الموردون", href: "/dashboard/suppliers", icon: Store },
      { title: "فواتير التوريد", href: "/dashboard/invoices", icon: ReceiptText },
      { title: "التحويلات الداخلية", href: "/dashboard/transfers", icon: Truck },
      { title: "طلبيات الأقسام", href: "/dashboard/purchase-orders", icon: ClipboardCheck },
      { title: "التالف والمحاريق", href: "/dashboard/waste", icon: PackageMinus },
      { title: "مرتجعات المخزن", href: "/dashboard/sales-returns", icon: RotateCcw },
      { title: "تقارير المخزن", href: "/dashboard/reports", icon: BarChart3 },
      { title: "تقرير تذبذب الأسعار", href: "/dashboard/reports?type=price_changes", icon: BarChart3 },
      { title: "تخصيص الأجهزة والأكواد", href: "/dashboard/settings/devices", icon: Tablet },
      { title: "الإعدادات / الأقسام", href: "/dashboard/settings", icon: Settings },
    ],
  },
];

export const adminNav = [
  { title: "لوحة الأدمن", href: "/admin", icon: Shield },
  { title: "طلبات التسجيل", href: "/admin/account-requests", icon: UserCheck },
  { title: "المؤسسات", href: "/admin/organizations", icon: Building2 },
  { title: "المستخدمون", href: "/admin/users", icon: Users },
  { title: "الخطط", href: "/admin/plans", icon: WalletCards },
  { title: "مفاتيح الميزات", href: "/admin/feature-flags", icon: Settings },
  { title: "سجلات النظام", href: "/admin/system-logs", icon: FileText },
  { title: "تذاكر الدعم", href: "/admin/support-tickets", icon: Bell },
];
